### ISSUE TITLE
No more daily increases visible on national views

### ISSUE THREAD

**Issue by bayquin** [mhdhejazi/CoronaTracker#117] opened 2020-05-18 07:03 UTC
Hi since last week I can no more see the board with the local/national daily increases, for example Germany! What happened?

**Comment by mhdhejazi** [comment] 2020-05-18 10:18
The issue is fixed here, and the fix will be included in the next update.
Are you using the macOS app or building from source?

**Comment by bayquin** [comment] 2020-05-20 05:54
I guess its the macOS App!

**Comment by blueguru** [comment] 2020-05-21 18:12
I have the exact same problem (with MacOS App). As the issues seems to befixed already, when will it be possible to release next update?
Would love to be able to see the detailed stats again :)

**Comment by mhdhejazi** [comment] 2020-05-21 20:55
Today then!

**Comment by blueguru** [comment] 2020-05-21 22:55
Awesome, thank you!

**Comment by mhdhejazi** [comment] 2020-05-22 00:12
Version 1.7.1 is available. Thank you for your feedback!

**Closed by mhdhejazi** 2020-05-22 00:12 UTC
