### ISSUE TITLE
No live map

### ISSUE THREAD

**Issue by Tijnderivecourt** [mhdhejazi/CoronaTracker#59] opened 2020-03-31 00:12 UTC
On the application I can't see the map with live stats. I can see all the graphs. Just not the map.
iPhone 11 Pro Max iOS 13.3

**Comment by mhdhejazi** [comment] 2020-03-31 01:23
Could you add a screenshot and more info about the environment (Xcode version, OS version, Device)?

**Comment by mhdhejazi** [comment] 2020-04-01 07:46
Duplicate of #60

**Closed** 2020-04-01 07:46 UTC
Labels: duplicate

**Comment by Tijnderivecourt** [comment] 2020-04-01 14:52
Dear Hejazi,

It's already fixed after I set the automatic time to manual! Maps now
working and everything is fine.

Thanks in advance!

Met vriendelijke groet,
Tijn de Rivecourt

**Comment by mhdhejazi** [comment] 2020-04-02 13:09
Well, that is weird! But glad you worked this out.
