### ISSUE TITLE
MacOS High Sierra with xcode 9.x

### ISSUE THREAD

**Issue by CryptoAngel** [mhdhejazi/CoronaTracker#128] opened 2020-07-17 10:55 UTC
Hi,
Great project!
What can I do to run this on MacOS High Sierra with xcode 9.x ?
Regards

**Comment by mhdhejazi** [comment] 2020-07-18 14:00
Unfortunately, the app doesn't work on macOS 10.14 or earlier. See #112

**Comment by mhdhejazi** [comment] 2020-07-18 14:00
Duplicate of #112

**Closed by mhdhejazi** 2020-07-18 14:00 UTC
